# Generated by Django 5.0.4 on 2024-05-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patient_image",
            field=models.ImageField(null=True, upload_to="patient image/"),
        ),
    ]
