# Generated by Django 5.0.4 on 2024-06-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Patient", "0002_patient_patient_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "staff_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("staff_name", models.CharField(max_length=300)),
                ("staff_email", models.EmailField(max_length=300)),
                ("staff_designation", models.CharField(max_length=300)),
                ("staff_password", models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_image",
            field=models.ImageField(null=True, upload_to="patient_image/"),
        ),
    ]
