# Generated by Django 5.0.4 on 2024-06-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Patient", "0003_staff_alter_patient_patient_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="staff_email",
            field=models.EmailField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="staff_password",
            field=models.CharField(editable=False, max_length=1000),
        ),
    ]
