# Generated by Django 5.1.1 on 2024-10-25 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bloggers",
            fields=[
                (
                    "blogger_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("first_name", models.CharField(max_length=300)),
                ("last_name", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("country", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=300)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="bloggers_profiles/"
                    ),
                ),
                ("password", models.CharField(max_length=3000)),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="published_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Blog.bloggers",
            ),
        ),
    ]
